# Generated by Django 5.1.1 on 2024-10-09 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='qualidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.location', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.location', verbose_name='Setor'),
        ),
    ]
