# Generated by Django 5.1.1 on 2024-10-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_grupos_qualidade_alter_notification_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupos',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
    ]
