# Generated by Django 5.1.1 on 2024-10-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0008_alter_grupos_qualidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='qualidade',
            field=models.BooleanField(default=False),
        ),
    ]
