# Generated by Django 5.1.1 on 2024-10-08 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quality', '0002_grupos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramenta5Porques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porque1', models.TextField(blank=True, null=True)),
                ('porque2', models.TextField(blank=True, null=True)),
                ('porque3', models.TextField(blank=True, null=True)),
                ('porque4', models.TextField(blank=True, null=True)),
                ('porque5', models.TextField(blank=True, null=True)),
                ('notificacao_evento_adverso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ferramentas_5porques', to='quality.notification')),
                ('oportunidade_melhoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ferramentas_5porques', to='quality.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='Ferramenta5W2H',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.TextField()),
                ('why', models.TextField()),
                ('where', models.TextField()),
                ('when', models.DateTimeField()),
                ('who', models.TextField()),
                ('how', models.TextField()),
                ('how_much', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notificacao_evento_adverso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ferramentas_5w2h', to='quality.notification')),
                ('oportunidade_melhoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ferramentas_5w2h', to='quality.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='FerramentaIshikawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema', models.TextField()),
                ('causas', models.TextField()),
                ('metodo', models.TextField(blank=True, null=True)),
                ('mao_de_obra', models.TextField(blank=True, null=True)),
                ('maquina', models.TextField(blank=True, null=True)),
                ('material', models.TextField(blank=True, null=True)),
                ('medicao', models.TextField(blank=True, null=True)),
                ('meio_ambiente', models.TextField(blank=True, null=True)),
                ('notificacao_evento_adverso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ferramentas_ishikawa', to='quality.notification')),
                ('oportunidade_melhoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ferramentas_ishikawa', to='quality.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='FerramentaSWOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forcas', models.TextField(blank=True, null=True)),
                ('fraquezas', models.TextField(blank=True, null=True)),
                ('oportunidades', models.TextField(blank=True, null=True)),
                ('ameacas', models.TextField(blank=True, null=True)),
                ('notificacao_evento_adverso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ferramentas_swot', to='quality.notification')),
                ('oportunidade_melhoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ferramentas_swot', to='quality.opportunity')),
            ],
        ),
    ]
