# Generated by Django 5.1.1 on 2024-10-10 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityTools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapeamentoSIPOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macroprocesso', models.CharField(max_length=255)),
                ('versao', models.CharField(max_length=255)),
                ('vigenca', models.CharField(max_length=255)),
                ('gestor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FerramentaSIPOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missao', models.TextField()),
                ('sistema', models.TextField()),
                ('equipe', models.TextField()),
                ('equipamentos', models.TextField()),
                ('produto', models.TextField()),
                ('resultado', models.TextField()),
                ('fornecedor', models.TextField()),
                ('entrada', models.TextField()),
                ('processo', models.ImageField(upload_to='qualityTools/processosSIPOC/photos/')),
                ('saida', models.TextField()),
                ('cliente', models.TextField()),
                ('mapeamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ferramentas_sipoc', to='qualityTools.mapeamentosipoc')),
            ],
        ),
    ]
