# Generated by Django 5.1.1 on 2024-10-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qualityTools', '0002_mapeamentosipoc_ferramentasipoc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapeamentosipoc',
            old_name='vigenca',
            new_name='vigencia',
        ),
    ]
