# Generated by Django 5.1.1 on 2024-10-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_appstool'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstool',
            name='taget',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
