# Generated by Django 5.1.1 on 2024-10-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0005_user_gestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='IDtasy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='default/users/photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='senha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
