# Generated by Django 5.1.1 on 2024-10-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0007_remove_user_gestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='IDtasy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(upload_to='default/users/photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='senha',
            field=models.CharField(max_length=50),
        ),
    ]
