# Generated by Django 5.1.1 on 2024-10-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0008_alter_user_idtasy_alter_user_foto_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='target',
            field=models.TextField(default='#'),
        ),
    ]
