# Generated by Django 5.1.1 on 2024-10-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0009_tool_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='target',
            field=models.TextField(default='_self'),
        ),
    ]
