# Generated by Django 5.1.1 on 2024-10-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0010_alter_tool_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(null=True, upload_to='default/users/photos/'),
        ),
    ]
